### ISSUE TITLE
Bug when disposing TcpClient

### ISSUE THREAD

**Issue by fabricedupre** [justcoding121/Titanium-Web-Proxy#328] opened 2017-11-14 18:48 UTC
A TcpClient is created and disposed in TcpConnection and ProxyServer.
Before each TcpClient.Dispose() call, TcpClient.LingerState is set to new LingerOption(true, 0).
Unfortunately, this raises an exception which prevents the call to TcpClient.Dispose() itself.
The more funny about this is that the exception is System.ObjectDisposedException on Socket.
I can easily comment the culprit line, but appears that
                        //This line is important!
                        //contributors please don't remove it without discussion
                        //It helps to avoid eventual deterioration of performance due to TCP port exhaustion
                        //due to default TCP CLOSE_WAIT timeout for 4 minutes
Maybe set the Linger State just after the TcpClient is created ?

**Comment by honfika** [comment] 2018-01-02 13:00
Duplicate of #107 
Please check that issue, I close this one.

**Closed by honfika** 2018-01-02 13:00 UTC
