### ISSUE TITLE
Access violation crypt32.pdb in Titanium.Web.Proxy.Examples.Wpf

### ISSUE THREAD

**Issue by dicehira** [justcoding121/Titanium-Web-Proxy#468] opened 2018-07-13 00:11 UTC
Using ver. 3.0.481 or 3.0.503, access violation of crypt32.pdb occurs in the example code (Example.Wpf).
When the application is built, no error occurs. But scanning network in a few minutes,  this error occurs.
I want to know the way to work around this error in latest version.

**Comment by justcoding121** [comment] 2018-07-13 18:57
Did you try latest beta? 

`Install-Package Titanium.Web.Proxy -Version 3.0.623-beta`

**Comment by dicehira** [comment] 2018-07-15 00:16
Thank you for your response. Same error occurs.
My environment is Windows10 (64bit) updated from Windows7.

**Comment by justcoding121** [comment] 2018-08-02 13:41
Is this a fatal error. Does it shutdown the proxy?

**Comment by nerodark** [comment] 2018-08-02 16:57
Yes the whole EXE crashes

**Comment by justcoding121** [comment] 2018-08-03 00:18
couple of more questions.

* Did anyone try switching the [certificate engine](https://justcoding121.github.io/Titanium-Web-Proxy/docs/api/Titanium.Web.Proxy.Network.CertificateManager.html#Titanium_Web_Proxy_Network_CertificateManager_CertificateEngine) and see this still happens.
* Happens only on .net 4.5 or in .Net core. What is the operating system.
* pdb files are usually in debug mode, if so does this happen in release mode too.

I am not sure on the cause and still looking to it. But this link may have some details for possible resolution.
https://support.microsoft.com/en-au/help/982416/an-application-that-uses-crypt32-dll-crashes-on-a-computer-that-is-run

**Comment by nerodark** [comment] 2018-08-04 04:56
It happened also in Release mode.
I also enabled this line of code because you were talking about certificate engine:
proxyServer.CertificateManager.CertificateEngine = Network.CertificateEngine.BouncyCastle;

and it seems to not happen anymore, at least not for the last 36 hours straight with heavy traffic. I have been testing it intensively. I am on windows 10.

I think this line of code is a good workaround for now :)

**Comment by justcoding121** [comment] 2018-09-22 00:37
Would appreciate if someone can find the cause of this error and suggest the fix.

**Comment by danucalovj** [comment] 2019-04-03 05:20
I had a similar issue with awaiting for responses and hanging the process, didn't get deep enough to see if it was related to certificate engine issues, but I created an if statement to check first is content length was greater than 0 and no further crashes observed.

**Comment by honfika** [comment] 2019-07-20 15:29
Can you reproduce the issue with the latest beta package?

**Comment by honfika** [comment] 2019-09-05 12:53
I close this isse, feel free to reopen if needed.

**Closed by honfika** 2019-09-05 12:53 UTC
Labels: bug, contributor wanted
