### ISSUE TITLE
Count of DataEventArgs is always 303

### ISSUE THREAD

**Issue by Luke03** [justcoding121/Titanium-Web-Proxy#566] opened 2019-03-11 12:40 UTC
I'm trying to implement a traffic monitor to limit traffic on my proxies.
I tried it like this:

```
private async Task Prox_AfterResponse(object sender, SessionEventArgs e)
        {
            e.DataReceived += E_DataReceived;
        }

        private void E_DataReceived(object sender, DataEventArgs e)
        {
            Console.WriteLine(e.Count);
            trafficCount += e.Count;
        }

        private async Task Prox_BeforeRequest(object sender, SessionEventArgs e)
        {
            e.DataSent += E_DataSent;
        }

        private void E_DataSent(object sender, DataEventArgs e)
        {
            Console.WriteLine(e.Count);
            trafficCount += e.Count;
        }
```

My problem is that e.Count always is 303, and I have no idea why.
Is there something I am doing wrong?

**Comment by honfika** [comment] 2019-04-24 14:28
In the WPF test project it seems to work. (Only the test project has a bug, I created a PR for it)

Could you please attach a simple test project which reproduces the issue?
Are you connection to websockets, or when do you expect data in this event?

**Comment by honfika** [comment] 2019-07-20 15:20
I close this issue, since I cannot reproduce it, and no answer from the author.
Feel free to repopen it if issue still exists.

**Closed by honfika** 2019-07-20 15:20 UTC
Labels: investigate
