### ISSUE TITLE
About the certificate

### ISSUE THREAD

**Issue by LexiSong67** [justcoding121/Titanium-Web-Proxy#594] opened 2019-05-29 10:32 UTC
I run the program, go to the page, it prompts【Couldn't authenticate host '10.134.134.48' with certificate '*.134.134.48'（Inner Exception：Authentication failed because the remote party closed the transport flow）】，and the page cannot be opened. What is the reason?What should I do?

**Comment by honfika** [comment] 2019-07-21 08:52
Please try the latest package.

**Comment by LexiSong67** [comment] 2019-08-01 08:12
Thank you for your answer.
However, I downloaded the latest version and still reported Error [Error occured whilst handling session request: due to unexpected packet format, handshake failure].
Now I find the reason, it should be that our program does not support TLS1.0.
How to support TLS1.0 protocol website?

**Comment by LexiSong67** [comment] 2019-08-07 10:32
@honfika Please have a look at it as soon as possible, now
I speculate that it may be necessary to reduce the version of the.net framework.What do you think?

**Comment by honfika** [comment] 2019-08-07 16:19
Is there a public site what i can use for testing this problem? Or how can I reproduce this issue?

**Comment by LexiSong67** [comment] 2019-08-08 00:52
@honfika This website only has internal network address, access needs to add VPN.I wonder if it is convenient for you to use QQ or any chat tools remote look at it?
By the way, is Titanium web-proxy available in.net framework4.0 or less?

**Comment by honfika** [comment] 2019-08-08 10:35
I don't know QQ, but I have hangouts, skype and viber, or we can use the TWP's gitter room (or a private chat there)

No, .net 4.0 is not available, because it is highly depend on the async programming, which is only available in .NET 4.5... but the minimum .NET version vas increased to .NET 4.6.1 recently.

**Comment by LexiSong67** [comment] 2019-08-09 01:38
@honfika Thank you for your patient reply.This is my skype account: JJSong1823@outlook.com.Let's make an appointment for you to look over the problem.

**Comment by honfika** [comment] 2019-08-16 20:30
This issue was fixed by the following commit: https://github.com/justcoding121/Titanium-Web-Proxy/commit/a5f42d7f40a697657f8792e2abe51b7e32790bb3

However I'll try to make it better.

We discussed it on Skype, so I'll close this issue. Feel free to reopen it or create a new issue when needed.

**Closed by honfika** 2019-08-16 20:30 UTC
