### ISSUE TITLE
Certificate for a proxy sitting on the same machine

### ISSUE THREAD

**Issue by XavAM** [justcoding121/Titanium-Web-Proxy#654] opened 2019-11-01 12:02 UTC
Hello, 

I am a beginner in using Titanium Proxy and, despite it's a fantastic tool, I am facing an issue which may be caused by my lack of knowledge of certificate management. 

I am using Titanium to connect to a bot-protected website via SSL, and I need to modify some requests on the fly.  

I use Selenium+Chrome (not headless) to connect to Titanium Proxy, and redirects the traffic to another transparent proxy. Titanium Proxy is sitting on the same machine as the browser.

    public class TitaniumProxy
    {
        private ProxyServer _proxyServer;

        public TitaniumProxy(int LocalHostPortNumber, string externalProxyIpAddress)
        {
            _proxyServer = new ProxyServer(true){};
      
            var explicitEndPoint = new ExplicitProxyEndPoint(System.Net.IPAddress.Any, LocalHostPortNumber, true)
            {            };

            _proxyServer.AddEndPoint(explicitEndPoint););
            _proxyServer.Start();
            _proxyServer.BeforeRequest += OnRequestCaptureTrafficEventHandler;

            _proxyServer.UpStreamHttpsProxy = new ExternalProxy();
            _proxyServer.UpStreamHttpsProxy.HostName = externalProxyIpAddress;
            _proxyServer.UpStreamHttpsProxy.Port = 1234;
            _proxyServer.UpStreamHttpsProxy.UserName = "username";
            _proxyServer.UpStreamHttpsProxy.Password = "password!!";
        }

This set up works well and I can easily sniff/modify HTTP requests  on many websites but it does not work on my target website : I get a captcha as soon as I connect.

I've made many tests and this issue comes from the Titanium proxy set up. For example, setting the **decryptSsl variable to false** on the ExplicitProxyEndpoint makes the captcha disappear on subsequent requests. But, I cannot modify requests going through anymore (can I?). 

My question is : I think the website detects that the certificate used by the proxy is not *acceptable*, so is it possible to re-use the certificate used by the client browser (Chrome) and where can I find it? Is it a windows default certificate?

Please apologize if this issue is due to a lack of knowledge on how HTTPS protocol works.

Thanks

**Comment by ByronAP** [comment] 2019-11-10 00:39
you don't send the certificate, the remote server does. Are you using some ip address that is marked as potentially dangerous like a public proxy? if you can get the request to not trigger the captcha using something like postman then I would then check what headers you are sending. If it triggers using the proxy through postman then the site is detecting the outgoing ip as potentially malicious or some other rule they have setup.

**Comment by XavAM** [comment] 2019-11-13 14:41
Hello @ByronAP , actually the remote server IP is not flagged : without Titanium proxy being between the browsing program and the remote proxy, it works like a charm. But once requests are going through Titanium with SSlDecrypt activated, IP is blocked instantly. 

I cannot find any header difference when pinging a remote webpage, but there may be some hidden fields I am not aware of.

**Comment by ByronAP** [comment] 2019-11-15 00:51
ok so once you enable decryption you can mess with the response however as you have noticed the caveat being that the data then needs to be re-encrypted and sent to the caller. Since the proxy does not have the signing certificate from the real host it makes a fake one and then re-encrypts it using that then returns it. Unless the fake certificate is trusted by your machine you will get errors.

Now as per the recaptcha i can think of a few things going on here... first is the recaptcha in an iframe? is there some script on the page that is detecting that the page has been served from an unexpected host?

**Comment by XavAM** [comment] 2019-11-15 16:35
Hello @ByronAP, 

> Unless the fake certificate is trusted by your machine you will get errors.

Actually no, the only error I get is from the website I am targeting. 

> first is the recaptcha in an iframe

No it's not.

>  is there some script on the page that is detecting that the page has been served from an unexpected host or that it has been modified?

They are plenty of scripts on the page trying to detect bots. That was my question, can they detect that the trafic has been through a Proxy **before** going through the remote proxy? 

When you say *you don't send the certificate, the remote server does*, I thought that the certificate wouldn't change whatever happens before reaching the proxy, does it?

**Comment by ByronAP** [comment] 2019-11-15 21:40
When ssl decrypt is enabled you have a flow like this... (this is a generic overview and does not show exactly how tls works but it's enough)

caller-request -> proxy -> remote host (returns cert1 and message) -> (decrypt message using cert1) proxy (encrypt with fake cert2) -> caller-response (caller aka u get cert 2 not cert 1)


Here you can see that the proxy is decrypting the data then re-encrypting it with a cert it has made on its own. This makes it easy for a client side script to see that the origin and cert are different.

SEE ALSO: https://stackoverflow.com/questions/2402121/within-a-web-browser-is-it-possible-for-javascript-to-obtain-information-about

If you disable ssl decryption then the certificate and everything else is forwarded along exactly as going through any other system and thus is completely transparent. (All traffic on the internet goes through a bunch of proxies/routers they just forward the packets instead of changing them)

**Comment by XavAM** [comment] 2019-11-16 11:01
Hmm ok clear, thanks for the explanation. So coming back to my first question, is there any way for proxy to use cert1 to reencrypt the traffic instead of fake cert2? Even when both (the browser + the proxy) are sitting on the same machine?

**Comment by honfika** [comment] 2019-11-16 22:16
Is it possible to reproduce this issue somehow? For example can you give me a limited VPN access only to that webserver?

**Comment by ByronAP** [comment] 2019-11-16 23:40
Sorry its not possible unless you have the private key of the original host.

**Comment by XavAM** [comment] 2019-11-17 09:05
@ByronAP alright. And the original host is ... Google Chrome?  Windows? A certificate that I own and I am not aware of? 
Thanks for your time and your explanations

**Comment by XavAM** [comment] 2019-11-17 09:10
@honfika It's kind of difficult to reproduce without the full set up in place. But, in private, I can give you more details and grant you an access to the Remote Proxy pool. How can I contact you?

**Comment by honfika** [comment] 2019-11-17 14:23
Skype? honfika_2

**Comment by XavAM** [comment] 2019-11-18 20:15
@ByronAP , I am confused then. What prevents the proxy to re-use cert1 when re-encrypting the traffic (I guess the traffic is encoded both ways so the caller uses it  to encrypt as well )? 

Btw, @honfika found what was causing the problem : there was a missing header space after re-encrypting the traffic.  This missing header was detected as suspicious by the website. 

Thanks to both of you for your time.

**Comment by honfika** [comment] 2019-11-18 21:28
May I close this issue?

**Comment by ByronAP** [comment] 2019-11-18 22:16
@XavAM "What prevents the proxy to re-use cert1" the proxy does not have the signing key for cert1 only its public key.

**Comment by honfika** [comment] 2019-11-30 12:13
The problem was solved (talked on Skype), so I close this issue. Feel free to reopen/create new issue if needed.

**Closed by honfika** 2019-11-30 12:13 UTC

**Comment by XavAM** [comment] 2020-01-03 18:59
Oh sorry, I missed the notification (and I only tested it today) but yes this issue can be closed, it works like a charm.  Thank you  very much @honfika for your commitment. 
Bottom line for a would be reader : this issue was not related to any certificate, it was a small bug sitting into the proxy code that @honfika has fixed.
