### ISSUE TITLE
Url unescape problem

### ISSUE THREAD

**Issue by ljh1991125** [justcoding121/Titanium-Web-Proxy#622] opened 2019-08-27 12:07 UTC
Hi.
Using this proxy i can not connect Microsoft One Drive.
I captured network traffic using fiddler and i found that there is problem in url unescaping.

![1](https://user-images.githubusercontent.com/41459974/63763881-32b9e900-c8f8-11e9-9d93-175d621a2f42.png)
![2](https://user-images.githubusercontent.com/41459974/63763882-32b9e900-c8f8-11e9-88d7-038e30a3797c.png)

First picture is the response and second is request.
As you can see response has location header so it is redirected.
But url in location header and url in redirected request is different.
Url in request is unescaped and "code%20id" is changed "code id".
So it failed to connect Microsoft One Drive.

I think following code cause problem because redirected url is not well-formed so it is unescaped.

```
            string url;
            if (useUpstreamProxy || isTransparent)
            {
                url = Request.RequestUriString;
            }
            else
            {
                var uri = Request.RequestUri;
                url = uri.IsWellFormedOriginalString() ? uri.PathAndQuery : uri.GetComponents(UriComponents.PathAndQuery, UriFormat.Unescaped);
            }
```

How can i solve this problem?
Thank you.

**Comment by honfika** [comment] 2019-08-27 13:12
This issue is duplicate of #596, please subscribe to that.

**Closed by honfika** 2019-08-27 13:12 UTC
