### ISSUE TITLE
Creating Certificate ERROR:  The FriendlyName value cannot be set on Unix.

### ISSUE THREAD

**Issue by bogdancice** [justcoding121/Titanium-Web-Proxy#324] opened 2017-11-06 15:38 UTC
Runtime Environment:
 OS Name:     ubuntu
 OS Version:  16.04
 OS Platform: Linux
 RID:         ubuntu.16.04-x64
Microsoft .NET Core Version  : 2.0.0

When creating a new X509 Certificate, I have an error in class
_BCCertificateMaker.NetStandard.cs_,
 _line 124_ -> _x509Certificate.FriendlyName = subjectName;_ 

the error message and the stack trace are:

```
System.PlatformNotSupportedException: The FriendlyName value cannot be set on Unix.
   at Internal.Cryptography.Pal.OpenSslX509CertificateReader.set_FriendlyName(String value)
   at System.Security.Cryptography.X509Certificates.X509Certificate2.set_FriendlyName(String value)
   at Titanium.Web.Proxy.Network.Certificate.BCCertificateMaker.GenerateCertificate(String hostName, String subjectName, String issuerName, DateTime validFrom, DateTime validTo, Int32 keyStrength, String signatureAlgorithm, AsymmetricKeyParameter issuerPrivateKey) in /home/ciceu/.../Titanium.Web.Proxy/Network/Certificate/BCCertificateMaker.NetStandard.cs:line 124
   at Titanium.Web.Proxy.Network.Certificate.BCCertificateMaker.MakeCertificateInternal(Boolean isRoot, String hostName, String subjectName, DateTime validFrom, DateTime validTo, X509Certificate2 signingCertificate) in /home/ciceu/.../Titanium.Web.Proxy/Network/Certificate/BCCertificateMaker.NetStandard.cs:line 167
   at Titanium.Web.Proxy.Network.Certificate.BCCertificateMaker.MakeCertificateInternal(String subject, Boolean isRoot, Boolean switchToMtaIfNeeded, X509Certificate2 signingCert, CancellationToken cancellationToken) in /home/ciceu/.../Titanium.Web.Proxy/Network/Certificate/BCCertificateMaker.NetStandard.cs:line 215
   at Titanium.Web.Proxy.Network.Certificate.BCCertificateMaker.MakeCertificate(String sSubjectCn, Boolean isRoot, X509Certificate2 signingCert) in /home/ciceu/.../Titanium.Web.Proxy/Network/Certificate/BCCertificateMaker.NetStandard.cs:line 42
   at Titanium.Web.Proxy.Network.CertificateManager.CreateCertificate(String certificateName, Boolean isRootCertificate) in /home/ciceu/.../Titanium.Web.Proxy/Network/CertificateManager.cs:line 382
```

Basically, the message is that:  _The FriendlyName value cannot be set on Unix._ 

The issue  https://github.com/aspnet/Home/issues/2038 seems to be simillar.

A Quick fix would be adding a try catch:
```
try{
 _x509Certificate.FriendlyName = subjectName;_ 
}
catch(Exception){} 
```
And the Certificate will be created with no FriendlyName

Has anyone else encountered this problem?

**Comment by honfika** [comment] 2017-11-19 12:50
I added the try-catch, but the related issue writes that it was fixed in 2.0 RTM. Which version of .NET Core do you use?

**Comment by bogdancice** [comment] 2017-11-21 09:03
Thanks for the reply. Yes, it's 2.0, I've checked again.

**Comment by honfika** [comment] 2017-12-28 20:26
I close this issue, since It is not a bug in TWP and a workaround (try-catch) was added

**Closed by honfika** 2017-12-28 20:26 UTC
