### ISSUE TITLE
WebSocket UPGRADE request issue

### ISSUE THREAD

**Issue by sergius-msv** [justcoding121/Titanium-Web-Proxy#471] opened 2018-07-17 08:41 UTC
I try using Titanium-Web-Proxy for WhatsApp web application https://web.whatsapp.com/.
WhatsApp web application hanging after sending WebSocket UPGRADE request to https://w{server-number}.web.whatsapp.com/ws endpoint. 

Server answering with HTTP status code 101

`HTTP/1.1 101 Switching Protocols`
`Upgrade: websocket`
`Connection: Upgrade`
`Sec-WebSocket-Accept: /+AKeVS4qZ0OzRDtAvt4bkYIsb8=`

But after that data is not transmitted through this connection.

Could you have a look for reason of this problem?

Thanks in advance!

**Comment by sergius-msv** [comment] 2018-09-12 12:34
QR code not appear... infinite loading...
![whatsappweb](https://user-images.githubusercontent.com/8350555/45425113-1c902a00-b6a1-11e8-9e47-9ce4652044a7.jpg)

**Comment by justcoding121** [comment] 2018-09-12 14:14
Interesting. But I can see it on Chrome windows with the latest version of proxy.

![image](https://user-images.githubusercontent.com/2637679/45430972-9bbb3900-b674-11e8-86ad-8db8b370de6d.png)

**Comment by DanilovAV** [comment] 2018-09-19 12:04
I have same problem, last version blocks websocket somehow, so I have same infinite loading on that whatsapp page, and other programs which uses websocket doesn't work at all if proxy is enabled. But old versions (I tried 3.0.213 and 3.0.130) don't have that issue, and work correctly.

**Comment by justcoding121** [comment] 2018-09-23 00:06
The issue appears to be happening in last stable version not in latest beta versions. That's the reason why I could'nt reproduce. I pushed latest beta as new stable 3.0.684. So this should be fixed in latest stable.

**Comment by kfreezen** [comment] 2018-10-01 19:34
I can report I'm having the same issue when using a transparent proxy endpoint. If I disable the transparent proxy check in WebSocketHandler.cs, I get a `101 Switching Protocols` but no data comes in on my client browser.

If I monitor DataSent and DataReceived, I can see that I'm getting data back from the server, but for some reason it's not making it back to the client browser.

**Comment by justcoding121** [comment] 2018-10-15 23:13
This should be fixed in latest beta. See #495

**Closed by justcoding121** 2018-10-15 23:13 UTC
Labels: bug
