### ISSUE TITLE
e.Buffer includes old data.

### ISSUE THREAD

**Issue by Zoe928** [justcoding121/Titanium-Web-Proxy#748] opened 2020-04-05 06:59 UTC
I need to get some WebSocket data, but the old data always shows up in “DataReceived”. which has never appeared before in other WebSocket connections. I suspect it is a bug. 

`
public Form1()
        {
            InitializeComponent();

            _proxy = new ProxyServer
            {
                ForwardToUpstreamGateway = true
            };

            var explicitEndPoint = new ExplicitProxyEndPoint(IPAddress.Any, 8000);
            explicitEndPoint.BeforeTunnelConnectRequest += ExplicitEndPoint_BeforeTunnelConnectRequest;
            _proxy.AddEndPoint(explicitEndPoint);
            _proxy.BeforeResponse += Proxy_BeforeResponse;

            _proxy.Start();

            // proxy.SetAsSystemProxy(explicitEndPoint, ProxyProtocolType.AllHttp);
        }
        
        private readonly ProxyServer _proxy;

        private async Task Proxy_BeforeResponse(object sender, SessionEventArgs e)
        {
            if (e.HttpClient.ConnectRequest?.TunnelType == TunnelType.Websocket)
            {
                e.DataReceived += E_DataReceived;
            }
        }

        private void E_DataReceived(object sender, DataEventArgs e)
        {
            var args = (SessionEventArgs)sender;
            foreach (var frame in args.WebSocketDecoder.Decode(e.Buffer, e.Offset, e.Count))
            {
                if (frame.OpCode == WebsocketOpCode.Text)
                {
                    var request = args.HttpClient.Request;
                    var text = frame.GetText();
                    Console.WriteLine(text);
                    /* Data handler */
                }
            }
        }
`

**Comment by honfika** [comment] 2020-04-05 08:03
Which old data? how to reproduce the bug? is there a public website?

**Comment by honfika** [comment] 2020-04-05 09:35
Anyway, the "e.Buffer includes old data" is true and it is not a bug.
You should use the e.Offset and e.Count parameters.

so e.Buffer contains new and valid data only from position e.Offset... and contains e.Count valid bytes.

**Comment by Zoe928** [comment] 2020-04-05 11:18
Ok, I just saw. Is this a feature? This problem didn’t appear when I test other WebSocket connections, thus I suspect it’s a bug. Thanks for replying.

**Comment by honfika** [comment] 2020-04-05 11:59
Yes, the buffer comes from a bufferpool (official System.Buffer.ArrayPool). which can contain memory garbage.

**Comment by Zoe928** [comment] 2020-04-05 14:09
Includes old frame data in the results of "args.WebSocketDecoder.Decode()". It is also normal?
code (reference example "ProxyTestController.cs"):
![2](https://user-images.githubusercontent.com/55832650/78500483-46300b00-7789-11ea-9ea2-e077ad5159f9.jpg)

output window: 
![1](https://user-images.githubusercontent.com/55832650/78500476-33b5d180-7789-11ea-969d-1d6466bf655e.jpg)

firefox network debug
![3](https://user-images.githubusercontent.com/55832650/78500507-6cee4180-7789-11ea-9e5b-030b976b581a.png)

**Comment by honfika** [comment] 2020-04-05 17:05
No, that is not normal... I've fixed it Please try the latest nuget package (3.1.1288)

**Comment by Zoe928** [comment] 2020-04-06 03:56
It is normally working.

**Comment by honfika** [comment] 2020-04-06 19:59
Ok, then I close this issue. feel fre to reopen if needed.

**Closed by honfika** 2020-04-06 19:59 UTC
