### ISSUE TITLE
Ipv6 only issue

### ISSUE THREAD

**Issue by bainbin** [justcoding121/Titanium-Web-Proxy#593] opened 2019-05-21 12:46 UTC
I'm trying the proxy when only Ipv6 is enabled on LAN.
explicit end point created with IPAddress.IPv6Loopback & proxy is set as system proxy.
The requests are intercepted, but no site is reachable. 
Not ivp6 only sites nor ipv6-test.com like ..

**Comment by ByronAP** [comment] 2019-08-18 20:57
similar issue here...  v6 only sitees fail with a could not establish connection error

Test Url: http://v6.testmyipv6.com/

**Comment by ByronAP** [comment] 2019-08-18 20:59
I think the issue is with port binding

**Comment by ByronAP** [comment] 2019-08-19 14:33
ok so local address issue solved by using 2 explicit endpoints, one for v4 and one for v6 both on the same port.  so now i can talk to the proxy using both 4 and 6 but calls dont go out over 6 only 4. This is my curl.

- V6: curl -k -6 -x [::1]:44444 https://v6.testmyipv6.com/ 

- V4: curl -k -6 -x [::1]:44444 https://v4.testmyipv6.com/ 

- Dual: curl -k -6 -x [::1]:44444 https://ds.testmyipv6.com/ 

all responses show only v4 requests out of the proxy...

**Comment by ByronAP** [comment] 2019-08-20 12:16
ok so it looks like after it does the dns resolution it then tries the available ip addresses. This issue here is that the tcp client has already been made and defaults to address family for v4 when in fact this can not be known until we are ready to try the connection. 

@justcoding121  ^bug?

**Comment by honfika** [comment] 2019-08-21 21:33
I'll check it in the weekend.

**Comment by ByronAP** [comment] 2019-08-21 23:04
ty here is where the connection is attempted but will fail https://github.com/justcoding121/Titanium-Web-Proxy/blob/master/src/Titanium.Web.Proxy/Network/Tcp/TcpConnectionFactory.cs#L315

I worked around it by moving the tcpclient creation inside the loop (with some added cleanup if it fails)

**Comment by honfika** [comment] 2019-08-26 17:31
Please try the latest beta build (will be released in some minutes)

**Comment by honfika** [comment] 2019-08-30 11:33
Dispose added.

**Comment by ByronAP** [comment] 2019-09-01 12:28
🙇 very nice...

**Comment by honfika** [comment] 2019-09-05 12:52
I close this isse, feel free to reopen if needed.

**Closed by honfika** 2019-09-05 12:52 UTC
